parameters:
  csp_parameters:
    default-src:
      - "'none'"
    script-src:
      - "'self'"
      - "'unsafe-inline'"
      - "'unsafe-eval'"
      - "https://cdn.matomo.cloud/histologe.matomo.cloud/matomo.js" # todo: remove when matomo is migrated to dinum tracker
      - "https://stats.beta.gouv.fr/matomo.js" # todo: remove when confirmed migration to dinum tracker
      - "https://stats.beta.gouv.fr/js/container_udgEriWD.js"
      - "https://cdn.jsdelivr.net/gh/nelmio/NelmioApiDocBundle/public/swagger-ui/"
      - "https://cdn.jsdelivr.net/gh/nelmio/NelmioApiDocBundle/public/"
    style-src:
      - "'self'"
      - "'unsafe-inline'"
      - "https://cdn.jsdelivr.net/gh/nelmio/NelmioApiDocBundle/public/swagger-ui/"
      - "https://cdn.jsdelivr.net/gh/nelmio/NelmioApiDocBundle/public/"
      - "https://fonts.googleapis.com"
    style-src-attr:
      - "'self'"
      - "'unsafe-inline'"
    img-src:
      - "'self'"
      - "data:"
      - "blob:"
      - "https://voxusagers.numerique.gouv.fr"
      - "https://*.tile.openstreetmap.org"
      - "https://tile.openstreetmap.org"
      - "https://cdn.jsdelivr.net"
      - "https://jedonnemonavis.numerique.gouv.fr"
      - "https://cdn.redoc.ly"
    connect-src:
      - "'self'"
      - "https://data.geopf.fr"
      - "https://cdn.matomo.cloud" # todo: remove when matomo is migrated to dinum tracker
      - "https://histologe.matomo.cloud" # todo: remove when matomo is migrated to dinum tracker
      - "https://stats.beta.gouv.fr" #new matomo
      - "https://koumoul.com"
      - "https://sentry.incubateur.net"
      - "https://rnb-api.beta.gouv.fr"
    font-src:
      - "'self'"
      - "https://fonts.gstatic.com"
    frame-src:
      - "'self'"
      - "blob:"
      - "https://histologe-metabase.osc-fr1.scalingo.io/"
    object-src:
      - "'self'"
      - "blob:"
    base-uri:
      - "'self'"
    form-action:
      - "'self'"
      - "%proconnect_scheme_protocol%%proconnect_domain%"
    frame-ancestors:
      - "'self'"
      - "https://signal-logement.beta.gouv.fr/"
      - "https://histologe-sites-faciles.osc-fr1.scalingo.io/"
      - "https://histologe-demo.osc-fr1.scalingo.io/"
      - "https://histologe-demo-sites-faciles.osc-fr1.scalingo.io/"
    media-src:
      - "'self'"
    worker-src:
      - "'self'"
      - "blob:"
    report-uri:
      - "/csp-report"
